### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jimford-sudo** [mudmin/AnotherMaker#1]
sudo apt-get install python-dev python-pip python-virtualenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package python-pip
E: Package 'python-virtualenv' has no installation candidate

**Comment by mudmin** [comment]
Thanks for helping work this out.  I got a lot of comments about why I didn't use this or that.  This thing was pretty tricky to get working.  I tried and gave up several times over the last few months until I got it working originally on an OrangePi on Ubuntu 18.  

Are those of you having problems on Pi 4B?  I think the instructions may be different for the 4b vs the 2/3.

**Comment by Eric738** [comment]
Bonjour
i follow your tups but after send cmd : opencanaryd --start i had some errors 👍 
--------------------------------------------------------
ubuntu@ubuntu:~$ opencanaryd --start
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python3.8/dist-packages/Twisted-19.10.0-py3.8-linux-aarch64.egg/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/bin/opencanary.tac", line 4, in <module>
    __import__('pkg_resources').run_script('opencanary==0.5.6', 'opencanary.tac')
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 663, in run_script
    name = ns['__name__']
builtins.KeyError: '__name__'


Failed to load application: '__name__'
-------------------------------------------------------
how i can fix these ?

thank for help and your work.
Eric

**Comment by Houdini7** [comment]
Looks like you're using Ubuntu 20.xx   Try ubuntu 18.xx
I had the same issues with 20.xx but redoing it with 18.xx worked fine for me

**Comment by mikeandamy1013** [comment]
yep, don't use ver20, use ver 18.  followed script and had no issues.  thank you for your help

**Comment by psu1989** [comment]
Any help with this on Pi3?

(env) pi@raspberrypi:~ $ opencanaryd --start
** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Failed to open /root/.opencanary.conf for reading ([Errno 2] No such file or directory: '/root/.opencanary.conf')
[-] Failed to open /etc/opencanaryd/opencanary.conf for reading ([Errno 2] No such file or directory: '/etc/opencanaryd/opencanary.conf')
/home/pi/env/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Can't import RDP. Please ensure you have RDP installed.
Can't import SNMP. Please ensure you have Scapy installed.
Error: config does not have 'logger' section

**Comment by mannydr3** [comment]
3 things; 1. Check what pip version you have and install Scapy if there is an applicable version for it. 2. Logger showing missing probably means the indentation in your config file is off, or is completely missing from the config.  3. RDP requires other modules being installed. I haven't been able to get that work yet. Ive made all my installs woth pip3 and python3

**Comment by Eric738** [comment]
ok thank i found : curl -sSL https://smnbkly.co/opencanary-installer | sudo bash on https://smnbkly.co/blog/opencanary-free-flexible-distributed-honeypot which in one cmd line...without smtp alert
